### ISSUE TITLE
Sentinel Golang Version V1 Discussions

### ISSUE THREAD

**Issue by louyuting** [sentinel-group/sentinel-golang#1]
# Describe what feature you want
Implement Golang version of Sentinel, including basic statistic and flow functions. Some expected features:

- Basic statistic structure (sliding window that can achieve high concurrency and accuracy)
- Rate limiting (based on token bucket algorithm, maybe we can leverage golang.org/x/time/rate.Limiter)
- Logging
- Metrics interface that can pump real-time metrics to outside consumer
- Embedded API server
- Integrate with Sentinel dashboard (machine discovery)

Discussions are welcomed!

**Comment by helloworldyuhaiyang** [comment]
I really need it.I have finished a golang project on internet,but not have Limiting ,Downgrade...   And i have read sentinel source code(java version and cpp),and write a little.Chain of responsibility have been finished,but Slot interface is not very sure,sliding window have been finished.My project is already running in production,i really need sentinel-golang
.I am a new golanger.Old driver brought me.

**Comment by sczyh30** [comment]
@helloworldyuhaiyang Contributions are welcomed! Maybe we could discuss the structure and design first.

@louyuting Any progress on this? :)

**Comment by helloworldyuhaiyang** [comment]
Is there a real-time communication tool,WeChat ,Dingding,Telegram,Twitter.I can do this this week,and need performance

**Comment by sczyh30** [comment]
> Is there a real-time communication tool,WeChat ,Dingding,Telegram,Twitter.I can do this this week,and need performance

We can discuss the design in this issue directly (so that the discussion could be public for all developers). And you could also join the Dingtalk group of Sentinel: 21977771

**Comment by helloworldyuhaiyang** [comment]
@louyuting @sczyh30
Can the slot of the responsibility chain are composed of the following interface.

type Slot interface {
	/**
	 * Entrance of this slots.
	 */
	Entry(context core.Context, resourceWrapper core.ResourceWrapper, param interface{}, count int, prioritized bool, args ...interface{}) (core.TokenResult, error)

	Exit(context core.Context, resourceWrapper core.ResourceWrapper, count int, args ...interface{}) (core.TokenResult, error)

	// 传递进入
	FireEntry(context core.Context, resourceWrapper core.ResourceWrapper, param interface{}, count int, prioritized bool, args ...interface{}) (core.TokenResult, error)

	// 传递退出
	FireExit(context core.Context, resourceWrapper core.ResourceWrapper, count int, args ...interface{}) (core.TokenResult, error)

	GetNext() Slot

	SetNext(next Slot)
}


type TokenResult struct {
	status int
	blockReason string
	waitMs uint64
}

**Comment by sanhuanshisanshao** [comment]
I am also interested in this project, look forward to joining.

**Comment by louyuting** [comment]
Recently,I have implement a test version to be tested. The repo is [louyuting/sentinel-golang](https://github.com/louyuting/sentinel-golang)  forked from [sentinel-group/sentinel-golang](https://github.com/sentinel-group/sentinel-golang). The test version haven't to do unit test and integration test. If you are interested in this, welcome to improve together.

**Comment by helloworldyuhaiyang** [comment]
> Recently,I have implement a test version to be tested. The repo is [louyuting/sentinel-golang](https://github.com/louyuting/sentinel-golang) forked from [sentinel-group/sentinel-golang](https://github.com/sentinel-group/sentinel-golang). The test version haven't to do unit test and integration test. If you are interested in this, welcome to improve together.

ok. i will contribute code to your repository.

**Comment by atuowgo** [comment]
is there a road map or some interface definition? i implement the [ratelimiter](https://github.com/atuowgo/ratelimiter) once refer to the java version,find that some concept or interface is suitable for the golang version.

**Comment by louyuting** [comment]
> is there a road map or some interface definition? i implement the [ratelimiter](https://github.com/atuowgo/ratelimiter) once refer to the java version,find that some concept or interface is suitable for the golang version.

Recently, we were discussing architectural design of golang version. And you could also join the Dingtalk group of Sentinel: 21977771

**Comment by atuowgo** [comment]
> > is there a road map or some interface definition? i implement the [ratelimiter](https://github.com/atuowgo/ratelimiter) once refer to the java version,find that some concept or interface is suitable for the golang version.
> 
> Recently, we were discussing architectural design of golang version. And you could also join the Dingtalk group of Sentinel: 21977771

yeah，i already in the Dingtalk from last year,but i din't receive from any discus about the go version,or maybe i miss it,expect to join the discuss

**Comment by sczyh30** [comment]
> yeah，i already in the Dingtalk from last year,but i din't receive from any discus about the go version,or maybe i miss it,expect to join the discuss

@atuowgo 群里 at 一下 宿何，我把你拉到 Golang 的讨论群里

**Comment by liangyuanpeng** [comment]
any update?

**Comment by louyuting** [comment]
under discussing.

**Comment by cgfork** [comment]
m

**Comment by sczyh30** [comment]
Sentinel Golang 0.1.0 has been released, so closing this umbrella issue. Thanks for all the contributors!

The introduction of Sentinel Golang v1 (CN): https://sentinelguard.io/zh-cn/blog/sentinel-golang-v1-go-go-go.html
