### ISSUE TITLE
[Bug] Atomic store for new bucket did not work as expected in BucketLeapArray.resetWindowTo

### ISSUE THREAD

**Issue by louyuting** [sentinel-group/sentinel-golang#22]
## Issue Description
BucketLeapArray.resetWindowTo bug.
Change windowWrap.value from interface{} to atomic.Value

Will fixed it.

**Comment by sczyh30** [comment]
Related code:

https://github.com/sentinel-group/sentinel-golang/blob/0bca355bb8274d4853e5c4e4c2df636b75eb42f7/core/stat/base/bucket_leap_array.go#L63-L72

**Comment by louyuting** [comment]
It would be fixed in PR:https://github.com/sentinel-group/sentinel-golang/pull/24
