### ISSUE TITLE
[Feature] General configuration (including config for logging)

### ISSUE THREAD

**Issue by louyuting** [sentinel-group/sentinel-golang#23]
## Issue Description
configurations when system start.
maybe use yaml or similar configuration file

**Comment by sczyh30** [comment]
We may support configuration via yaml file or system env. Hard-coded configuration may also be supported if needed.

**Comment by sczyh30** [comment]
The definition overview of the config (v1):

```go
type Config struct {
	Version  string
	Sentinel struct {
		App struct {
			// Name represents the name of current running service.
			Name string
			// Type indicates the classification of the service (e.g. web service, API gateway).
			Type int32
		}
		Log struct {
			// Dir represents the log directory path.
			Dir string
			// UsePid indicates whether the filename ends with the process ID (PID).
			UsePid bool
			// Metric represents the configuration items of the metric log.
			Metric struct {
				SingleFileMaxSize uint64
				MaxFileCount      uint32
				FlushIntervalSec  uint32
			}
		}
	}
}
```

**Comment by sczyh30** [comment]
It's supported to configure some fundamental items from the system env, like appName and logDir.

Some items do not support configuring by file, so users need to configure them via system env or hard-coding manually:

- The file path of the yaml file (optional)
- The logging directory
