### ISSUE TITLE
[BUG] Data-Race for metricBucket.addRt

### ISSUE THREAD

**Issue by gorexlv** [sentinel-group/sentinel-golang#26]
## Issue Description

```golang
func (mb *metricBucket) addRt(rt int64) {
	mb.add(base.MetricEventRt, rt)
	if rt < atomic.LoadInt64(&mb.minRt) {
		atomic.StoreInt64(&mb.minRt, rt)
	}
}
```

here, not concurrent safe for `mb.minRt`.  It's better to use Mutex

another missing:
```golang
func (n *BaseStatNode) AddRtAndCompleteRequest(rt, count uint64) {
	n.rollingCounter.AddCount(base.MetricEventComplete, int64(count))
	n.rollingCounter.AddCount(base.MetricEventRt, int64(count)) // should be `rt`
}
```

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

Thanks for your work.

**Comment by louyuting** [comment]
For Question1:
Yes, it's not concurrent safe, but it's ok. Mutex is too heavy. The performance is more important here.

For Question2:
Will be fixed in PR: [Issue13 circuit breaker slot and general property model](https://github.com/sentinel-group/sentinel-golang/pull/18.)

Thanks for your work.

**Comment by louyuting** [comment]
Furthermore, for question1, it's not the data race issue, in fact, it's concurrent safe issue.

**Comment by gorexlv** [comment]
Actually, It will cause `data race panic/warning` if concurrently call addRt. 

```
func Test_addRt(t *testing.T) {
	var wg sync.WaitGroup
	mb := newMetricBucket()
	wg.Add(1000)

	for i := 0; i < 1000; i++ {
		go func() {
			mb.addRt(int64(i))
			wg.Done()
		}()
	}
	wg.Wait()
}
```
```bash
go test --run=addRt --race
```

another potential code: 
```
func (mb *metricBucket) get(event base.MetricEvent) int64 {
	if event > base.MetricEventTotal || event < 0 {
		panic(fmt.Sprintf("Event %v is unknown.", event))
	}
	return mb.counter[event]  // here, no atomic lock protection
}
```

At present, I'm not sure if the `caller` will call addRt or get/setMetricEvent concurrently.  If not, there's really no problem :)

**Comment by louyuting** [comment]
For Question about: "Test_addRt "
Based on your code, here is the result on running test -race:
```
WARNING: DATA RACE
Read at 0x00c0000f8738 by goroutine 9:
  github.com/sentinel-group/sentinel-golang/core/stat/base.Test_addRt.func1()
      /Users/ytlou/Desktop/golang/sentinel-golang/core/stat/base/metric_bucket_test.go:61 +0x38

Previous write at 0x00c0000f8738 by goroutine 8:
  github.com/sentinel-group/sentinel-golang/core/stat/base.Test_addRt()
      /Users/ytlou/Desktop/golang/sentinel-golang/core/stat/base/metric_bucket_test.go:59 +0x165
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 9 (running) created at:
  github.com/sentinel-group/sentinel-golang/core/stat/base.Test_addRt()
      /Users/ytlou/Desktop/golang/sentinel-golang/core/stat/base/metric_bucket_test.go:60 +0x141
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:92 +0x223
==================
--- FAIL: Test_addRt (0.06s)
    testing.go:853: race detected during execution of test
FAIL
exit status 1
FAIL    github.com/sentinel-group/sentinel-golang/core/stat/base        0.712s
```
In fact, the data race occur on var "i".

Please see test:
```
func Test_addRt(t *testing.T) {
	var wg sync.WaitGroup
	mb := newMetricBucket()
	wg.Add(1000)
	
	for i := 0; i < 1000; i++ {
		go func() {
			ad := rand.Int()%1000
			mb.addRt(int64(ad))
			wg.Done()
		}()
	}
	wg.Wait()
}
```
run `go test --race` will pass

**Comment by louyuting** [comment]
The root cause is that, variable "i" is the competitor.

**Comment by louyuting** [comment]
About metricBucket.get().

Yes, it should be atomic.LoadInt64(&mb.counter[event]).  

Thanks for your work.

**Comment by gorexlv** [comment]
yes, you're right. here it's the problem of `testing code`.
It's concurrent unsafe or data-inaccuracy but not data-race. 
thanks.

**Comment by louyuting** [comment]
You are welcome~Thanks for your advice about some bugs.

**Comment by louyuting** [comment]
According to the feedbacks from @sczyh30 ,he had known these data race issues above and  he is doing integration test and would fixed these issues.

Would you have another other suggestion about these issues above.

**Comment by gorexlv** [comment]
No suggestion by now. I will keep an eye on this project, it's amazing. Thank you. You've done a great job.

**Comment by sczyh30** [comment]
I'm working on rearranging existing code (including statistic, flow control, circuit breaking, system adaptive flow control and metric log) and doing initial integration test. I'll sumbit the PR of the flow and metric log module later.  Suggestions and contributions are welcomed! @gorexlv
