### ISSUE TITLE
Rule based flow control

### ISSUE THREAD

**Issue by louyuting** [sentinel-group/sentinel-golang#4]
## Issue Description
Rule based flow control

### Describe what feature you want
Implement flow slot based on core pipeline. flow slot is stateless and implements flow control based on rules.

Each rule can have its own window length, different window length is very important to degrade service.

### Additional context

1. timestamp align for all sliding windows.
2. rule can be injected or deleted dynamically. 
3. multi traffic shaping controllers

**Comment by sczyh30** [comment]
This could be split into the following parts:

- Statistic and metrics
  - The basic statistic data structure (sliding window); The Node and SlidingWindowMetric hierarchy
  - The `StatisticSlot`
- Rule manager (relevant to the design of data-source)
- FlowSlot and flow checker strategies (including the TrafficShapingController hierarchy

**Comment by louyuting** [comment]
duplicate https://github.com/sentinel-group/sentinel-golang/issues/12
