### ISSUE TITLE
golang版本的dashboard有吗？还是说可以直接用java的dashboard jar包呢?

### ISSUE THREAD

**Issue by joe9724** [sentinel-group/sentinel-golang#44]
## Issue Description

Type: *feature request*

**Comment by louyuting** [comment]
The Java version of dashboard will be reused and the interface will be consistent.
The golang version will plug in dashboard in future versions.

There is a existed issue to describe this question: https://github.com/sentinel-group/sentinel-golang/issues/20 . I will close this.

Thanks.
