### ISSUE TITLE
[Feature] Data-source and data property listener

### ISSUE THREAD

**Issue by sczyh30** [sentinel-group/sentinel-golang#7]
## Issue Description

Type: *feature request*

### Describe what feature you want

Data-source and data property listener (`SentinelProperty` and `PropertyListener` in Java). Some considerations:

- We might need to support multiple `SentinelProperty` (with different parsers) shared by the single data-source.

**Comment by sczyh30** [comment]
As Golang lacks generic type at present, we might have to leave the value type as `interface{}` in `SentinelProperty` and `PropertyListener` :(

**Comment by sczyh30** [comment]
We may improve our design in the next version. Using channel to handle data propagating might be better (also in Golang style).

**Comment by louyuting** [comment]
I would add the general Property model in PR: [https://github.com/sentinel-group/sentinel-golang/pull/18](https://github.com/sentinel-group/sentinel-golang/pull/18)

**Comment by louyuting** [comment]
We might use channel of golang to implement this feature.
